# Generated by Django 3.2 on 2021-04-23 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('location', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('ISBN', models.CharField(default='000', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='request_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=datetime.datetime(2021, 4, 30, 12, 2, 57, 650692, tzinfo=utc))),
                ('request_status', models.CharField(default='Pending', max_length=15)),
                ('book_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
