# Generated by Django 3.2 on 2021-04-23 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_request_detail_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_detail',
            name='return_date',
        ),
        migrations.AddField(
            model_name='request_detail',
            name='duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='request_detail',
            name='requested_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 13, 42, 54, 798722, tzinfo=utc)),
        ),
    ]
