# Generated by Django 3.2 on 2021-04-24 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_request_detail_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_detail',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 6, 47, 51, 621980, tzinfo=utc)),
        ),
    ]
