# Generated by Django 3.2 on 2021-04-24 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_request_detail_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_detail',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 9, 21, 37, 52272, tzinfo=utc)),
        ),
    ]
